import os
import sys
from supabase import create_client, Client

# Adicionar diretório do projeto ao path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Importar cliente Supabase existente
from supabase_client import supabase

# Lista de paletas para adicionar
paletas = [
    {
        'nome': 'Azul Royal',
        'slug': 'azul-royal',
        'descricao': 'Paleta elegante com tons de azul royal profissional',
        'icone': '👔',
        'ativo': True,
        'sort_order': 4,
        'cor_fundo_principal': '#0a1628',
        'cor_fundo_secundario': '#0f2744',
        'cor_titulos': '#f0f9ff',
        'cor_texto': '#e0f2fe',
        'cor_texto_secundario': '#94a3b8',
        'cor_surface': '#ffffff',
        'botao_primario_bg': '#1e40af',
        'botao_primario_texto': '#ffffff',
        'botao_primario_hover': '#1e3a8a',
        'botao_secundario_bg': '#334155',
        'botao_secundario_texto': '#ffffff',
        'botao_secundario_hover': '#1e293b',
        'botao_destaque_bg': '#0ea5e9',
        'botao_destaque_texto': '#ffffff',
        'botao_destaque_hover': '#0284c7',
        'botao_neutro_bg': '#e2e8f0',
        'botao_neutro_texto': '#0f172a',
        'botao_neutro_hover': '#cbd5e1'
    },
    {
        'nome': 'Verde Esmeralda',
        'slug': 'verde-esmeralda',
        'descricao': 'Paleta sofisticada com tons de verde esmeralda',
        'icone': '💎',
        'ativo': True,
        'sort_order': 5,
        'cor_fundo_principal': '#022c22',
        'cor_fundo_secundario': '#064e3b',
        'cor_titulos': '#ecfdf5',
        'cor_texto': '#d1fae5',
        'cor_texto_secundario': '#94a3b8',
        'cor_surface': '#ffffff',
        'botao_primario_bg': '#059669',
        'botao_primario_texto': '#ffffff',
        'botao_primario_hover': '#047857',
        'botao_secundario_bg': '#334155',
        'botao_secundario_texto': '#ffffff',
        'botao_secundario_hover': '#1e293b',
        'botao_destaque_bg': '#10b981',
        'botao_destaque_texto': '#ffffff',
        'botao_destaque_hover': '#059669',
        'botao_neutro_bg': '#e2e8f0',
        'botao_neutro_texto': '#0f172a',
        'botao_neutro_hover': '#cbd5e1'
    },
    {
        'nome': 'Roxo Nobre',
        'slug': 'roxo-nobre',
        'descricao': 'Paleta luxuosa com tons de roxo nobre',
        'icone': '👑',
        'ativo': True,
        'sort_order': 6,
        'cor_fundo_principal': '#1e1b4b',
        'cor_fundo_secundario': '#312e81',
        'cor_titulos': '#f5f3ff',
        'cor_texto': '#ede9fe',
        'cor_texto_secundario': '#94a3b8',
        'cor_surface': '#ffffff',
        'botao_primario_bg': '#7c3aed',
        'botao_primario_texto': '#ffffff',
        'botao_primario_hover': '#6d28d9',
        'botao_secundario_bg': '#334155',
        'botao_secundario_texto': '#ffffff',
        'botao_secundario_hover': '#1e293b',
        'botao_destaque_bg': '#a78bfa',
        'botao_destaque_texto': '#ffffff',
        'botao_destaque_hover': '#8b5cf6',
        'botao_neutro_bg': '#e2e8f0',
        'botao_neutro_texto': '#0f172a',
        'botao_neutro_hover': '#cbd5e1'
    },
    {
        'nome': 'Laranja Queimado',
        'slug': 'laranja-queimado',
        'descricao': 'Paleta vibrante com tons de laranja queimado',
        'icone': '🔥',
        'ativo': True,
        'sort_order': 7,
        'cor_fundo_principal': '#1c1917',
        'cor_fundo_secundario': '#292524',
        'cor_titulos': '#fff7ed',
        'cor_texto': '#ffedd5',
        'cor_texto_secundario': '#94a3b8',
        'cor_surface': '#ffffff',
        'botao_primario_bg': '#ea580c',
        'botao_primario_texto': '#ffffff',
        'botao_primario_hover': '#c2410c',
        'botao_secundario_bg': '#334155',
        'botao_secundario_texto': '#ffffff',
        'botao_secundario_hover': '#1e293b',
        'botao_destaque_bg': '#f97316',
        'botao_destaque_texto': '#ffffff',
        'botao_destaque_hover': '#ea580c',
        'botao_neutro_bg': '#e2e8f0',
        'botao_neutro_texto': '#0f172a',
        'botao_neutro_hover': '#cbd5e1'
    },
    {
        'nome': 'Rosa Profundo',
        'slug': 'rosa-profundo',
        'descricao': 'Paleta elegante com tons de rosa profundo',
        'icone': '🌹',
        'ativo': True,
        'sort_order': 8,
        'cor_fundo_principal': '#1f1f1f',
        'cor_fundo_secundario': '#292524',
        'cor_titulos': '#fdf2f8',
        'cor_texto': '#fce7f3',
        'cor_texto_secundario': '#94a3b8',
        'cor_surface': '#ffffff',
        'botao_primario_bg': '#db2777',
        'botao_primario_texto': '#ffffff',
        'botao_primario_hover': '#be185d',
        'botao_secundario_bg': '#334155',
        'botao_secundario_texto': '#ffffff',
        'botao_secundario_hover': '#1e293b',
        'botao_destaque_bg': '#ec4899',
        'botao_destaque_texto': '#ffffff',
        'botao_destaque_hover': '#db2777',
        'botao_neutro_bg': '#e2e8f0',
        'botao_neutro_texto': '#0f172a',
        'botao_neutro_hover': '#cbd5e1'
    },
    {
        'nome': 'Ciano Profissional',
        'slug': 'ciano-profissional',
        'descricao': 'Paleta moderna com tons de ciano profissional',
        'icone': '💼',
        'ativo': True,
        'sort_order': 9,
        'cor_fundo_principal': '#083344',
        'cor_fundo_secundario': '#0e7490',
        'cor_titulos': '#ecfeff',
        'cor_texto': '#cffafe',
        'cor_texto_secundario': '#94a3b8',
        'cor_surface': '#ffffff',
        'botao_primario_bg': '#0891b2',
        'botao_primario_texto': '#ffffff',
        'botao_primario_hover': '#0e7490',
        'botao_secundario_bg': '#334155',
        'botao_secundario_texto': '#ffffff',
        'botao_secundario_hover': '#1e293b',
        'botao_destaque_bg': '#06b6d4',
        'botao_destaque_texto': '#ffffff',
        'botao_destaque_hover': '#0891b2',
        'botao_neutro_bg': '#e2e8f0',
        'botao_neutro_texto': '#0f172a',
        'botao_neutro_hover': '#cbd5e1'
    },
    {
        'nome': 'Cinza Grafite',
        'slug': 'cinza-grafite',
        'descricao': 'Paleta minimalista com tons de cinza grafite',
        'icone': '⬛',
        'ativo': True,
        'sort_order': 10,
        'cor_fundo_principal': '#0f172a',
        'cor_fundo_secundario': '#1e293b',
        'cor_titulos': '#f8fafc',
        'cor_texto': '#f1f5f9',
        'cor_texto_secundario': '#94a3b8',
        'cor_surface': '#ffffff',
        'botao_primario_bg': '#475569',
        'botao_primario_texto': '#ffffff',
        'botao_primario_hover': '#334155',
        'botao_secundario_bg': '#334155',
        'botao_secundario_texto': '#ffffff',
        'botao_secundario_hover': '#1e293b',
        'botao_destaque_bg': '#64748b',
        'botao_destaque_texto': '#ffffff',
        'botao_destaque_hover': '#475569',
        'botao_neutro_bg': '#e2e8f0',
        'botao_neutro_texto': '#0f172a',
        'botao_neutro_hover': '#cbd5e1'
    },
    {
        'nome': 'Azul Meia-noite',
        'slug': 'azul-meia-noite',
        'descricao': 'Paleta elegante com tons de azul meia-noite',
        'icone': '🌙',
        'ativo': True,
        'sort_order': 11,
        'cor_fundo_principal': '#020617',
        'cor_fundo_secundario': '#0f172a',
        'cor_titulos': '#f0f9ff',
        'cor_texto': '#e0f2fe',
        'cor_texto_secundario': '#94a3b8',
        'cor_surface': '#ffffff',
        'botao_primario_bg': '#0284c7',
        'botao_primario_texto': '#ffffff',
        'botao_primario_hover': '#0369a1',
        'botao_secundario_bg': '#334155',
        'botao_secundario_texto': '#ffffff',
        'botao_secundario_hover': '#1e293b',
        'botao_destaque_bg': '#0ea5e9',
        'botao_destaque_texto': '#ffffff',
        'botao_destaque_hover': '#0284c7',
        'botao_neutro_bg': '#e2e8f0',
        'botao_neutro_texto': '#0f172a',
        'botao_neutro_hover': '#cbd5e1'
    },
    {
        'nome': 'Dourado Luxo',
        'slug': 'dourado-luxo',
        'descricao': 'Paleta sofisticada com tons de dourado luxo',
        'icone': '✨',
        'ativo': True,
        'sort_order': 12,
        'cor_fundo_principal': '#1c1917',
        'cor_fundo_secundario': '#292524',
        'cor_titulos': '#fffbeb',
        'cor_texto': '#fef3c7',
        'cor_texto_secundario': '#94a3b8',
        'cor_surface': '#ffffff',
        'botao_primario_bg': '#b45309',
        'botao_primario_texto': '#ffffff',
        'botao_primario_hover': '#92400e',
        'botao_secundario_bg': '#334155',
        'botao_secundario_texto': '#ffffff',
        'botao_secundario_hover': '#1e293b',
        'botao_destaque_bg': '#f59e0b',
        'botao_destaque_texto': '#ffffff',
        'botao_destaque_hover': '#d97706',
        'botao_neutro_bg': '#e2e8f0',
        'botao_neutro_texto': '#0f172a',
        'botao_neutro_hover': '#cbd5e1'
    },
    {
        'nome': 'Prata Moderno',
        'slug': 'prata-moderno',
        'descricao': 'Paleta contemporânea com tons de prata moderno',
        'icone': '🔘',
        'ativo': True,
        'sort_order': 13,
        'cor_fundo_principal': '#0f172a',
        'cor_fundo_secundario': '#1e293b',
        'cor_titulos': '#f8fafc',
        'cor_texto': '#f1f5f9',
        'cor_texto_secundario': '#94a3b8',
        'cor_surface': '#ffffff',
        'botao_primario_bg': '#64748b',
        'botao_primario_texto': '#ffffff',
        'botao_primario_hover': '#475569',
        'botao_secundario_bg': '#334155',
        'botao_secundario_texto': '#ffffff',
        'botao_secundario_hover': '#1e293b',
        'botao_destaque_bg': '#94a3b8',
        'botao_destaque_texto': '#ffffff',
        'botao_destaque_hover': '#64748b',
        'botao_neutro_bg': '#e2e8f0',
        'botao_neutro_texto': '#0f172a',
        'botao_neutro_hover': '#cbd5e1'
    },
    {
        'nome': 'Vinho Tinto',
        'slug': 'vinho-tinto',
        'descricao': 'Paleta elegante com tons de vinho tinto',
        'icone': '🍷',
        'ativo': True,
        'sort_order': 14,
        'cor_fundo_principal': '#1c1c1c',
        'cor_fundo_secundario': '#2d2d2d',
        'cor_titulos': '#fdf2f8',
        'cor_texto': '#fce7f3',
        'cor_texto_secundario': '#94a3b8',
        'cor_surface': '#ffffff',
        'botao_primario_bg': '#9f1239',
        'botao_primario_texto': '#ffffff',
        'botao_primario_hover': '#881337',
        'botao_secundario_bg': '#334155',
        'botao_secundario_texto': '#ffffff',
        'botao_secundario_hover': '#1e293b',
        'botao_destaque_bg': '#be123c',
        'botao_destaque_texto': '#ffffff',
        'botao_destaque_hover': '#9f1239',
        'botao_neutro_bg': '#e2e8f0',
        'botao_neutro_texto': '#0f172a',
        'botao_neutro_hover': '#cbd5e1'
    },
    {
        'nome': 'Azul Petróleo',
        'slug': 'azul-petroleo',
        'descricao': 'Paleta refinada com tons de azul petróleo',
        'icone': '🔵',
        'ativo': True,
        'sort_order': 15,
        'cor_fundo_principal': '#0f172a',
        'cor_fundo_secundario': '#1e3a5f',
        'cor_titulos': '#f0f9ff',
        'cor_texto': '#e0f2fe',
        'cor_texto_secundario': '#94a3b8',
        'cor_surface': '#ffffff',
        'botao_primario_bg': '#0c4a6e',
        'botao_primario_texto': '#ffffff',
        'botao_primario_hover': '#075985',
        'botao_secundario_bg': '#334155',
        'botao_secundario_texto': '#ffffff',
        'botao_secundario_hover': '#1e293b',
        'botao_destaque_bg': '#0284c7',
        'botao_destaque_texto': '#ffffff',
        'botao_destaque_hover': '#0369a1',
        'botao_neutro_bg': '#e2e8f0',
        'botao_neutro_texto': '#0f172a',
        'botao_neutro_hover': '#cbd5e1'
    },
    {
        'nome': 'Bronze Clássico',
        'slug': 'bronze-classico',
        'descricao': 'Paleta tradicional com tons de bronze clássico',
        'icone': '🏆',
        'ativo': True,
        'sort_order': 16,
        'cor_fundo_principal': '#1c1917',
        'cor_fundo_secundario': '#292524',
        'cor_titulos': '#fffbeb',
        'cor_texto': '#fef3c7',
        'cor_texto_secundario': '#94a3b8',
        'cor_surface': '#ffffff',
        'botao_primario_bg': '#a16207',
        'botao_primario_texto': '#ffffff',
        'botao_primario_hover': '#854d0e',
        'botao_secundario_bg': '#334155',
        'botao_secundario_texto': '#ffffff',
        'botao_secundario_hover': '#1e293b',
        'botao_destaque_bg': '#ca8a04',
        'botao_destaque_texto': '#ffffff',
        'botao_destaque_hover': '#a16207',
        'botao_neutro_bg': '#e2e8f0',
        'botao_neutro_texto': '#0f172a',
        'botao_neutro_hover': '#cbd5e1'
    },
    {
        'nome': 'Índigo Místico',
        'slug': 'indigo-mistico',
        'descricao': 'Paleta misteriosa com tons de índigo místico',
        'icone': '🔮',
        'ativo': True,
        'sort_order': 17,
        'cor_fundo_principal': '#1e1b4b',
        'cor_fundo_secundario': '#312e81',
        'cor_titulos': '#eef2ff',
        'cor_texto': '#e0e7ff',
        'cor_texto_secundario': '#94a3b8',
        'cor_surface': '#ffffff',
        'botao_primario_bg': '#4338ca',
        'botao_primario_texto': '#ffffff',
        'botao_primario_hover': '#3730a3',
        'botao_secundario_bg': '#334155',
        'botao_secundario_texto': '#ffffff',
        'botao_secundario_hover': '#1e293b',
        'botao_destaque_bg': '#6366f1',
        'botao_destaque_texto': '#ffffff',
        'botao_destaque_hover': '#4f46e5',
        'botao_neutro_bg': '#e2e8f0',
        'botao_neutro_texto': '#0f172a',
        'botao_neutro_hover': '#cbd5e1'
    },
    {
        'nome': 'Marrom Café',
        'slug': 'marrom-cafe',
        'descricao': 'Paleta acolhedora com tons de marrom café',
        'icone': '☕',
        'ativo': True,
        'sort_order': 18,
        'cor_fundo_principal': '#1c1917',
        'cor_fundo_secundario': '#292524',
        'cor_titulos': '#fff7ed',
        'cor_texto': '#ffedd5',
        'cor_texto_secundario': '#94a3b8',
        'cor_surface': '#ffffff',
        'botao_primario_bg': '#78350f',
        'botao_primario_texto': '#ffffff',
        'botao_primario_hover': '#451a03',
        'botao_secundario_bg': '#334155',
        'botao_secundario_texto': '#ffffff',
        'botao_secundario_hover': '#1e293b',
        'botao_destaque_bg': '#d97706',
        'botao_destaque_texto': '#ffffff',
        'botao_destaque_hover': '#b45309',
        'botao_neutro_bg': '#e2e8f0',
        'botao_neutro_texto': '#0f172a',
        'botao_neutro_hover': '#cbd5e1'
    }
]

# Adicionar cada paleta ao banco de dados
print("Iniciando inserção de 15 paletas predefinidas...")
for paleta in paletas:
    try:
        # Verificar se slug já existe
        existente = supabase.table('paletas_predefinidas').select('*').eq('slug', paleta['slug']).execute()
        if existente.data:
            print(f"Paleta '{paleta['nome']}' já existe, pulando...")
            continue

        # Inserir paleta
        result = supabase.table('paletas_predefinidas').insert(paleta).execute()
        if result.data:
            print(f"✓ Paleta '{paleta['nome']}' inserida com sucesso!")
        else:
            print(f"✗ Erro ao inserir paleta '{paleta['nome']}'")
    except Exception as e:
        print(f"✗ Erro ao inserir paleta '{paleta['nome']}': {e}")

print("Processo concluído!")
